const SetCars = () => {
    if (localStorage.getItem("cars1") === null) {
        const cars1 = [
            {
                "title": "Porsche 911 GT3",
                "price": 200000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2019,
                "mileage": "5K mi",
                "engine": "6.0L TS+",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Chicago",
                "agent": "Amy Walker",
                "added": "23.02.24",
                "image": "./src/images/porsche911GT3.jpg"
            },
            {
                "title": "Audi A4",
                "price": 800,
                "priceType": "rent per week",
                "model": "Sedan",
                "year": 2018,
                "mileage": "18K mi",
                "engine": "2.5L TD+",
                "fuel": "Diesel",
                "transmission": "Automatic",
                "city": "Detroit",
                "agent": "Frank Lewis",
                "added": "22.02.24",
                "image": "./src/images/audiA4.jpg"
            },
            {
                "title": "Audi RS6",
                "price": 14500,
                "priceType": "sale",
                "model": "Wagon",
                "year": 2018,
                "mileage": "20K mi",
                "engine": "1.6L CPNA",
                "fuel": "Gasoline",
                "transmission": "Manual",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "21.02.24",
                "image": "./src/images/audiRS6.jpg"
            },
            {
                "title": "Audi RS7",
                "price": 88000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2012,
                "mileage": "15K mi",
                "engine": "6.0L TS+",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Miami",
                "agent": "Frank Lewis",
                "added": "20.02.24",
                "image": "./src/images/audiRS7.jpg"
            },
            {
                "title": "Toyota C-HR",
                "price": 1000,
                "priceType": "rent per week",
                "model": "Hatchback",
                "year": 2014,
                "mileage": "50K mi",
                "engine": "4.0L Turbo",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "19.02.24",
                "image": "./src/images/toyotaC-HR.jpg"
            },
            {
                "title": "BMW 1 Series",
                "price": 70000,
                "priceType": "sale",
                "model": "Hatchback",
                "year": 2017,
                "mileage": "10K mi",
                "engine": "3.0L TDI+",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Miami",
                "agent": "Frank Lewis",
                "added": "18.02.24",
                "image": "./src/images/BMW1Series.jpg"
            }
        ];

        localStorage.setItem("cars1", JSON.stringify(cars1));
    }

    if (localStorage.getItem("cars2") === null) {
        const cars2 = [
            {
                "title": "Porsche 911 GT3",
                "price": 200000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2019,
                "mileage": "5K mi",
                "engine": "6.0L TS+",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Chicago",
                "agent": "Amy Walker",
                "added": "23.02.24",
                "image": "./src/images/porsche911GT3.jpg"
            },
            {
                "title": "Audi A4",
                "price": 800,
                "priceType": "rent per week",
                "model": "Sedan",
                "year": 2018,
                "mileage": "18K mi",
                "engine": "2.5L TD+",
                "fuel": "Diesel",
                "transmission": "Automatic",
                "city": "Detroit",
                "agent": "Frank Lewis",
                "added": "22.02.24",
                "image": "./src/images/audiA4.jpg"
            },
            {
                "title": "Audi RS6",
                "price": 14500,
                "priceType": "sale",
                "model": "Wagon",
                "year": 2018,
                "mileage": "20K mi",
                "engine": "1.6L CPNA",
                "fuel": "Gasoline",
                "transmission": "Manual",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "21.02.24",
                "image": "./src/images/audiRS6.jpg"
            },
            {
                "title": "Audi RS7",
                "price": 88000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2012,
                "mileage": "15K mi",
                "engine": "6.0L TS+",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Miami",
                "agent": "Frank Lewis",
                "added": "20.02.24",
                "image": "./src/images/audiRS7.jpg"
            },
            {
                "title": "Toyota C-HR",
                "price": 1000,
                "priceType": "rent per week",
                "model": "Hatchback",
                "year": 2014,
                "mileage": "50K mi",
                "engine": "4.0L Turbo",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "19.02.24",
                "image": "./src/images/toyotaC-HR.jpg"
            },
            {
                "title": "BMW 1 Series",
                "price": 70000,
                "priceType": "sale",
                "model": "Hatchback",
                "year": 2017,
                "mileage": "10K mi",
                "engine": "3.0L TDI+",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Miami",
                "agent": "Frank Lewis",
                "added": "18.02.24",
                "image": "./src/images/BMW1Series.jpg"
            },
            {
                "title": "Audi R8",
                "price": 100000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2016,
                "mileage": "50K mi",
                "engine": "4.2L FSI",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Chicago",
                "agent": "Amy Walker",
                "added": "17.02.24",
                "image": "./src/images/audiR8.jpg"
            },
            {
                "title": "BMW M4",
                "price": 800,
                "priceType": "rent per week",
                "model": "Coupe",
                "year": 2004,
                "mileage": "100K mi",
                "engine": "5.4L TS+",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Seattle",
                "agent": "Frank Lewis",
                "added": "16.02.24",
                "image": "./src/images/BMWM4.jpg"
            },
            {
                "title": "Porsche 718",
                "price": 200000,
                "priceType": "sale",
                "model": "Sport",
                "year": 2019,
                "mileage": "100K mi",
                "engine": "3.9L Turbo",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "15.02.24",
                "image": "./src/images/porsche718.jpg"
            },
            {
                "title": "Mercedes AMG 35",
                "price": 90000,
                "priceType": "sale",
                "model": "Sedan",
                "year": 2024,
                "mileage": "10K mi",
                "engine": "6.5L Turbo",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Detroit",
                "agent": "Jim Carter",
                "added": "14.02.24",
                "image": "./src/images/mercedesAMG35.jpg"
            },
            {
                "title": "BMW M3",
                "price": 20000,
                "priceType": "sale",
                "model": "Wagon",
                "year": 2008,
                "mileage": "54K mi",
                "engine": "3.1L Turbo",
                "fuel": "Diesel",
                "transmission": "Automatic",
                "city": "Chicago",
                "agent": "Jim Carter",
                "added": "13.02.24",
                "image": "./src/images/BMWM3.jpg"
            },
            {
                "title": "BMW M2",
                "price": 80000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2018,
                "mileage": "94K mi",
                "engine": "4.4L Turbo",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Detroit",
                "agent": "Jim Carter",
                "added": "12.02.24",
                "image": "./src/images/BMWM2.jpg"
            }
        ];

        localStorage.setItem("cars2", JSON.stringify(cars2));
    }

    if (localStorage.getItem("cars3") === null) {
        const cars3 = [
            {
                "title": "Porsche 911 GT3",
                "price": 200000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2019,
                "mileage": "5K mi",
                "engine": "6.0L TS+",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Chicago",
                "agent": "Amy Walker",
                "added": "23.02.24",
                "image": "./src/images/porsche911GT3.jpg"
            },
            {
                "title": "Audi A4",
                "price": 800,
                "priceType": "rent per week",
                "model": "Sedan",
                "year": 2018,
                "mileage": "18K mi",
                "engine": "2.5L TD+",
                "fuel": "Diesel",
                "transmission": "Automatic",
                "city": "Detroit",
                "agent": "Frank Lewis",
                "added": "22.02.24",
                "image": "./src/images/audiA4.jpg"
            },
            {
                "title": "Audi RS6",
                "price": 14500,
                "priceType": "sale",
                "model": "Wagon",
                "year": 2018,
                "mileage": "20K mi",
                "engine": "1.6L CPNA",
                "fuel": "Gasoline",
                "transmission": "Manual",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "21.02.24",
                "image": "./src/images/audiRS6.jpg"
            },
            {
                "title": "Audi RS7",
                "price": 88000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2012,
                "mileage": "15K mi",
                "engine": "6.0L TS+",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Miami",
                "agent": "Frank Lewis",
                "added": "20.02.24",
                "image": "./src/images/audiRS7.jpg"
            },
            {
                "title": "Toyota C-HR",
                "price": 1000,
                "priceType": "rent per week",
                "model": "Hatchback",
                "year": 2014,
                "mileage": "50K mi",
                "engine": "4.0L Turbo",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "19.02.24",
                "image": "./src/images/toyotaC-HR.jpg"
            },
            {
                "title": "BMW 1 Series",
                "price": 70000,
                "priceType": "sale",
                "model": "Hatchback",
                "year": 2017,
                "mileage": "10K mi",
                "engine": "3.0L TDI+",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Miami",
                "agent": "Frank Lewis",
                "added": "18.02.24",
                "image": "./src/images/BMW1Series.jpg"
            },
            {
                "title": "Audi R8",
                "price": 100000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2016,
                "mileage": "50K mi",
                "engine": "4.2L FSI",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Chicago",
                "agent": "Amy Walker",
                "added": "17.02.24",
                "image": "./src/images/audiR8.jpg"
            },
            {
                "title": "BMW M4",
                "price": 800,
                "priceType": "rent per week",
                "model": "Coupe",
                "year": 2004,
                "mileage": "100K mi",
                "engine": "5.4L TS+",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Seattle",
                "agent": "Frank Lewis",
                "added": "16.02.24",
                "image": "./src/images/BMWM4.jpg"
            },
            {
                "title": "Porsche 718",
                "price": 200000,
                "priceType": "sale",
                "model": "Sport",
                "year": 2019,
                "mileage": "100K mi",
                "engine": "3.9L Turbo",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Seattle",
                "agent": "Amy Walker",
                "added": "15.02.24",
                "image": "./src/images/porsche718.jpg"
            },
            {
                "title": "Mercedes AMG 35",
                "price": 90000,
                "priceType": "sale",
                "model": "Sedan",
                "year": 2024,
                "mileage": "10K mi",
                "engine": "6.5L Turbo",
                "fuel": "Gasoline",
                "transmission": "Automatic",
                "city": "Detroit",
                "agent": "Jim Carter",
                "added": "14.02.24",
                "image": "./src/images/mercedesAMG35.jpg"
            },
            {
                "title": "BMW M3",
                "price": 20000,
                "priceType": "sale",
                "model": "Wagon",
                "year": 2008,
                "mileage": "54K mi",
                "engine": "3.1L Turbo",
                "fuel": "Diesel",
                "transmission": "Automatic",
                "city": "Chicago",
                "agent": "Jim Carter",
                "added": "13.02.24",
                "image": "./src/images/BMWM3.jpg"
            },
            {
                "title": "BMW M2",
                "price": 80000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2018,
                "mileage": "94K mi",
                "engine": "4.4L Turbo",
                "fuel": "Gasoline",
                "transmission": "Tiptronic",
                "city": "Detroit",
                "agent": "Jim Carter",
                "added": "12.02.24",
                "image": "./src/images/BMWM2.jpg"
            },
            {
                "title": "Tesla Model 3",
                "price": 30000,
                "priceType": "sale",
                "model": "Sedan",
                "year": 2021,
                "mileage": "65K mi",
                "engine": "825 bhp AC",
                "fuel": "Electric",
                "transmission": "Automatic",
                "city": "Seattle",
                "agent": "Jim Carter",
                "added": "11.02.24",
                "image": "./src/images/teslaModel3.jpg"
            },
            {
                "title": "Tesla Model X",
                "price": 40000,
                "priceType": "sale",
                "model": "Coupe",
                "year": 2021,
                "mileage": "45K mi",
                "engine": "660 bhp DC",
                "fuel": "Electric",
                "transmission": "Automatic",
                "city": "Chicago",
                "agent": "Jim Carter",
                "added": "10.02.24",
                "image": "./src/images/teslaModelX.jpg"
            },
            {
                "title": "Audi Q4 e-tron",
                "price": 40000,
                "priceType": "sale",
                "model": "SUV",
                "year": 2024,
                "mileage": "22K mi",
                "engine": "540 bhp AC",
                "fuel": "Electric",
                "transmission": "Automatic",
                "city": "Detroit",
                "agent": "Jim Carter",
                "added": "09.02.24",
                "image": "./src/images/audiQ4e-tron.jpg"
            },
            {
                "title": "Hyundai Ioniq",
                "price": 20000,
                "priceType": "sale",
                "model": "Sedan",
                "year": 2023,
                "mileage": "10K mi",
                "engine": "400 bhp DC",
                "fuel": "Electric",
                "transmission": "Automatic",
                "city": "Miami",
                "agent": "Jim Carter",
                "added": "08.02.24",
                "image": "./src/images/hyundaiIoniq.jpg"
            }
        ];

        localStorage.setItem("cars3", JSON.stringify(cars3));
    }
}

export default SetCars;

